# Generated by Django 4.0.4 on 2022-05-21 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_admin"),
    ]

    operations = [
        migrations.CreateModel(
            name="NinInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_brith", models.DateField()),
                ("state_of_origin", models.CharField(max_length=30)),
                ("state", models.CharField(max_length=30)),
                ("address", models.TextField()),
                ("next_of_kin", models.CharField(max_length=100)),
                ("next_of_kin_address", models.TextField()),
                ("occupation", models.CharField(max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
