# Generated by Django 4.0.4 on 2022-05-21 01:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_nininfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='admin_type',
        ),
        migrations.AddField(
            model_name='admin',
            name='type',
            field=models.CharField(blank=True, choices=[('Local Goverment', 'Local Goverment'), ('State Goverment', 'State Goverment'), ('Federal Goverment', 'Federal Goverment')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('type', models.CharField(choices=[('Old National ID Card', 'Old National ID Card'), ('Driver’s License', 'Driver’s License'), ('Voter’s card (Temporary or Permanent)', 'Voter’s card (Temporary or Permanent)'), ('Nigerian International passport', 'Nigerian International passport'), ('Certificate of Origin', 'Certificate of Origin')], max_length=100)),
                ('path', models.FileField(upload_to='documents/')),
                ('nin_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nininfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
