# Generated by Django 4.0.4 on 2022-05-21 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_remove_admin_admin_type_admin_type_document"),
    ]

    operations = [
        migrations.CreateModel(
            name="Request",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("field", models.CharField(max_length=100)),
                ("old_value", models.CharField(max_length=250)),
                ("new_value", models.CharField(max_length=250)),
                ("document_path", models.FileField(upload_to="documents/")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Pending"),
                            (1, "Disapproved"),
                            (2, "Verified"),
                            (3, "Approved"),
                        ],
                        default=0,
                    ),
                ),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="api.admin",
                    ),
                ),
                (
                    "nin_info",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.nininfo"
                    ),
                ),
                ("create_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("update_at", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
