# Generated by Django 4.0.4 on 2022-05-21 17:24

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_request'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', api.models.UserManager()),
            ],
        ),
    ]
