# Generated by Django 4.0.4 on 2022-05-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_is_admin_user_is_citizen_alter_admin_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_citizen',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
