# Generated by Django 4.0.4 on 2022-06-20 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_is_admin_user_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='nininfo',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='nininfo',
            name='genotype',
            field=models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='nininfo',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divoreced', 'Divoreced')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='nininfo',
            name='next_of_kin_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='nininfo',
            name='next_of_kin_phone',
            field=models.TextField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='type',
            field=models.CharField(blank=True, choices=[('Local Government', 'Local Government'), ('State Government', 'State Government'), ('Federal Government', 'Federal Government')], max_length=30, null=True),
        ),
    ]
