# Generated by Django 4.0.4 on 2022-06-20 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_nininfo_blood_group_nininfo_genotype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nininfo',
            name='state',
        ),
    ]
