# Generated by Django 4.0.4 on 2022-06-25 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_nininfo_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nininfo',
            old_name='user',
            new_name='citizen',
        ),
    ]
