# Generated by Django 4.0.4 on 2022-06-27 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_rename_user_nininfo_citizen'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('encodings', models.TextField()),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.citizen')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
