# Generated by Django 4.0.4 on 2022-07-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_rename_date_of_brith_nininfo_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
