# Generated by Django 4.0.4 on 2022-07-04 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_user_email'),
        ('api', '0017_user_middle_name'),
    ]

    operations = [
    ]
