# Generated by Django 4.0.4 on 2022-07-04 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_document_path_alter_document_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdocument',
            name='document',
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='certificate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='api.document'),
        ),
        migrations.AddField(
            model_name='educationdocument',
            name='transcript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transcript', to='api.document'),
        ),
    ]
