# Generated by Django 4.0.4 on 2022-07-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_access_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateNinInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('state_of_origin', models.CharField(max_length=30)),
                ('address', models.TextField()),
                ('marital_status', models.CharField(blank=True, choices=[('Single', 'Single'), ('Married', 'Married'), ('Divoreced', 'Divoreced')], max_length=30, null=True)),
                ('blood_group', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=10, null=True)),
                ('genotype', models.CharField(blank=True, choices=[('AA', 'AA'), ('AS', 'AS'), ('AC', 'AC'), ('SS', 'SS')], max_length=2, null=True)),
                ('next_of_kin', models.CharField(max_length=100)),
                ('next_of_kin_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('next_of_kin_phone', models.TextField(blank=True, max_length=11, null=True)),
                ('next_of_kin_address', models.TextField()),
                ('occupation', models.CharField(max_length=100)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.citizen')),
                ('nin_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.nininfo')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
