# Generated by Django 4.0.4 on 2022-07-12 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_updatenininfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nininfo',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='updatenininfo',
            name='next_of_kin_phone',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
