# Generated by Django 4.0.4 on 2022-07-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_nininfo_next_of_kin_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='status',
        ),
        migrations.AddField(
            model_name='updatenininfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Disapproved'), (2, 'Completed'), (3, 'Approved')], default=0),
        ),
    ]
