# Generated by Django 4.0.4 on 2022-07-23 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_request_status_updatenininfo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='NIMC/qrcodes'),
        ),
    ]
